### ISSUE TITLE
QUIZZ

### ISSUE THREAD

**Issue by Sekooly** [Sekooly/SUPABASE#131]
# Besoin
Les NON élèves peuvent créer 2 types de quizz (catégorie à part!):
- auto-évaluation : résultat immédiat (nombre de tentatives autorisées > 0) -> pas de notification de rendu
- d'examen : résultat en différé sous validation du propriétaire du quizz (rendu comme un devoir) (tentatives = 1) : timer ? -> avec notification de rendu

Les élèves rendent directement le devoir lorsqu'ils valident le questionnaire.

Il y a 3 types de réponses:
- saisie libre (espaces non comptés, virgule avec un .)
- choix multiple (checkbox)
- choix unique (radio button)

# Solution
## Créer la table Quiz: 
    - id_quiz (text)
    - id_classe_matiere (text)
    - proprietaire (text)
    - titre (text)
    - description (text)
    - questions (json en string): [intitule_question, choix_possibles, reponse_valide, remarque_ok, remarque_nok]
    - resultat_immediat (boolen)
    - nb_tentatives (integer): vaut 1 par défaut, surtout si resultat_immediat = true
    - questions_aleatoires (booleen)
    - date_publication (par defaut VIDE -> mode brouillon)
    - remarque_fin (text): facultatif - pour sondages par exemple
### 1 - Général
Choisir le titre, la description
### 2 - Conception (CUD dans CRUD)
Titre de la question
Type de réponse
Liste des réponses
Réponse(s) juste(s)
Remarque si ok / nok (facultatif)
### 3 - Derniere mise au point
Résultat immédiat ou en attente de validation (tentative=1) ?
Nombre de tentatives autorisées (ssi résultat immédiat) ?
Questions aléatoires ?
Test du professeur (mode testing)
Publier (mettre une date) ou mode brouillon ?
#### Si SANS date de publication: SANS notif 
id_fichier: id_quiz 
id_dossier: dossier_chargé
categorie_fichier: Quiz
proprietaire: identifiant_courant
nom_fichier: titre du quiz
date_effet: **à choisir**
la_date_limite: **à choisir**
lheure_limite: **à choisir**
est_telechargeable: NON
coefficient: à choisir
taille_fichier: utiliser la fonction taille_fichier_quiz
id_chapitre: **à choisir**
date_publication: SSI c'est publié

#### Si avec date de publication: notif également
- choisir les champs "à choisir"
- notifier

## Créer la logique au clic du fichier Quiz (testable par un professeur) - R dans CRUD
- Mode création (cf points précédents) pour le prof
- Mode testing pour les élèves
#### b) Pour chaque question:
    - b1) Afficher l’intitulé
    - b2) Afficher les réponses possibles (ou un simple input)
    - b3) Bouton suivant: **sauvegarde auto**
    - b4) Bouton précédent: **sauvegarde auto**
    - b5) aller à la question n°X: **sauvegarde auto**
    - b6) récapitulatif des réponses (TOUT afficher d'un coup): **sauvegarde auto**
    - b7) sauvegarder pour plus tard (PAS de date de publication)
    - b8) tout envoyer (AVEC date de publication)

#### c) après l'envoi final:
    - **immédiat** : afficher mon score final, et SSI mes tentatives (table Rendus) < tentatives autorisées, ajouter le bouton Recommencer
    - **en attente**: afficher "Ce quiz est en attente de correction de l'enseignant. Vous ne pouvez plus le modifier. Pour visualiser vos réponses, cliquez **ici**."

## A faire
- [x] Créer la catégorie spécifique Quiz dans la liste déroulante 
- [x] Créer la catégorie spécifique Quiz dans les drives
- [x] Taille d'un fichier : utiliser la fonction `taille_fichier_quiz(liste_questions_str)`
- [x] Ajouter une colonne reponses dans la table Rendus
- [x] Voir le quiz comme un devoir/examen (!! à considérer pour les tdb, clics droits, etc.!!)
- [x] Voir la réponse du quiz comme étant un rendu de devoir
- [x] Si je ne publie pas -> en mode brouillon (mettre **NON PUBLIÉ** en rouge) : visible uniquement si je suis le proprio
- [x] Si je publie -> Notifier le nouveau fichier, créer le fichier dont le id est l'id du quizz

**Comment by Sekooly** [comment]
# Pour simplifier : nouvelle table Questions

`CREATE TABLE (id_quiz text, id_question integer, intitule_question text, choix_possibles text, reponse_valide integer, remarque_ok text DEFAULT '✅ Votre réponse est correcte.',  remarque_nok text DEFAULT '❌ Votre réponse est incorrecte.', CONSTRAINT fk_id_quiz FOREIGN KEY(id_quiz ) REFERENCES "Quiz"(id_quiz))`

**Comment by Sekooly** [comment]
# Todo - créer 2 tables supplémentaires
## Questions
```
CREATE TABLE "Questions" (

id_quiz text,
id_question text,
position_question integer,
type_question text,
intitule_question text,


PRIMARY KEY(id_quiz, id_question)
);
```


## Reponses

```
CREATE TABLE "Reponses" (

id_quiz text,
id_question text,
id_reponse text,
position_reponse integer,
intitule_reponse text,
score integer,
remarque_correction text,

PRIMARY KEY(id_quiz, id_question,id_reponse)
);
```

**Comment by Sekooly** [comment]
![image](https://user-images.githubusercontent.com/73037199/120115750-6ee14400-c185-11eb-914a-4076aab4e08a.png)

**Comment by Sekooly** [comment]
# Exemple d'écran pour finaliser le quiz
![image](https://user-images.githubusercontent.com/73037199/120118049-cb962c00-c190-11eb-80b6-4b2179f3e9a0.png)
