### ISSUE TITLE
Fenêtre en mode superposé

### ISSUE THREAD

**Issue by Sekooly** [Sekooly/SUPABASE#142]
# Problématique
Quand on regarde une vidéo et qu'on veut lire un fichier en même temps.
Quand on veut lire la leçon et le devoir en même temps.
Quand on veut appeler en visio et consulter un fichier en même temps.

# Solution
Créer un raccourci pour détacher la fenêtre, et créer une instance non supprimable a la fermeture de la fenêtre principale

# TODO
- [ ] créer le bouton de pop-up
- [ ] transformer la fenêtre en pop-up ET garder la (nouvelle) fenêtre initiale
- [ ] transformer le quitter_previz du nouveau pop-up (non écrasé quand on change de fenêtre)
- [ ] revenir au mode écran standard

# Attention
- 1 seul pop up possible
- 1 seule fenêtre principale possible
