### ISSUE TITLE
Options des établissements

### ISSUE THREAD

**Issue by Sekooly** [Sekooly/SUPABASE#154]
# Problème
Des options de trop

# Solution
Modifier `function au_clic(selector, callback)` en regardant si l'option est 
- compris dans le pack: toujours présent
- facultative:
    - [ ] si l'établissement y a souscrit : afficher avec la bonne fonction (déjà actuel)
    - [ ] si l'établissement n'y a PAS souscrit : sans fonction, puis supprimer l'élément,

**Comment by Sekooly** [comment]
# Avant tout
Choisir les options dans Infos établissement

# Comment
Lister toutes les options (non comprises)
Cocher ce qui est utile
Enregistrer

**Comment by Sekooly** [comment]
```
var opt= await recherche_initiale("my_options")
opt = a.filter(e => e.taux_option > 0)

```

**Comment by Sekooly** [comment]
# Liste des options possibles
- [ ] Préférences
- [ ] Emploi du temps
- [ ] Quiz
- [ ] Multi-visio
- [ ] Bulletins scolaires
- [ ] Remédiations
- [ ] Conseil de classe


# Todo
- [ ] Faire choisir les options par un admin de tout droit
- [ ] Définir les options comprises dans le contrat
- [ ] Ré-éditer le contrat en interne (côté client)
- [ ] Enlever des options sous 30 jours
- [ ] Ajouter des options immédiatement
- [ ]
