### ISSUE TITLE
Relevé / Attestation

### ISSUE THREAD

**Issue by jadynekena** [Sekooly/SUPABASE#169]
# Bulletins
Rendre optionnelle

# Attestation / certificat
Creer le fichier dynamiquement.
Cf https://javascript-ninja.fr/docxtemplater/v1/examples/demo.html

# Todos
- [ ] importer le template
- [ ] vérifier que le template a tous les champs requis (logo, nom, prénom, date, nom du module, etc)
- [ ] mettre en ligne le template
- [ ] a la génération du pdf : injecter les données et télécharger en PDF
